// Datos de caracteres chinos (Hanzi) organizados por nivel de dificultad.
// Los niveles 1 a 6 siguen la clasificación clásica de HSK (Hànyǔ Shuǐpíng
// Kǎoshì): los caracteres se derivan de las palabras oficiales de cada
// nivel de HSK (descomponiendo cada palabra en sus caracteres individuales
// y asignando cada carácter al nivel HSK donde aparece por primera vez),
// para que los niveles bajos cubran los caracteres más comunes y los
// niveles altos cubran vocabulario más avanzado. Los niveles 7 y 8 son
// contenido extra (clásico y de nicho) que va más allá del temario de HSK.
// Fuente de datos HSK: https://github.com/drkameleon/complete-hsk-vocabulary

const LEVELS = [
  {
    id: 1,
    name: "Nivel 1 · HSK 1 (Básico)",
    chars: [
      { char: "的", pinyin: "de", meaning: "partícula posesiva (de)" },
      { char: "了", pinyin: "le", meaning: "partícula de acción completada" },
      { char: "我", pinyin: "wǒ", meaning: "yo" },
      { char: "是", pinyin: "shì", meaning: "ser / estar" },
      { char: "你", pinyin: "nǐ", meaning: "tú" },
      { char: "在", pinyin: "zài", meaning: "estar (en) / en" },
      { char: "不", pinyin: "bù", meaning: "no" },
      { char: "有", pinyin: "yǒu", meaning: "tener / haber" },
      { char: "他", pinyin: "tā", meaning: "él" },
      { char: "这", pinyin: "zhè", meaning: "este / esto" },
      { char: "个", pinyin: "gè", meaning: "clasificador general" },
      { char: "和", pinyin: "hé", meaning: "y (conjunción)" },
      { char: "人", pinyin: "rén", meaning: "persona" },
      { char: "们", pinyin: "men", meaning: "sufijo de plural (personas)" },
      { char: "好", pinyin: "hǎo", meaning: "bueno" },
      { char: "一", pinyin: "yī", meaning: "uno" },
      { char: "会", pinyin: "huì", meaning: "saber (habilidad) / reunión" },
      { char: "都", pinyin: "dōu", meaning: "todos / incluso" },
      { char: "对", pinyin: "duì", meaning: "correcto / hacia" },
      { char: "上", pinyin: "shàng", meaning: "arriba / subir" },
      { char: "来", pinyin: "lái", meaning: "venir" },
      { char: "很", pinyin: "hěn", meaning: "muy" },
      { char: "去", pinyin: "qù", meaning: "ir" },
      { char: "她", pinyin: "tā", meaning: "ella" },
      { char: "想", pinyin: "xiǎng", meaning: "pensar / querer" },
      { char: "能", pinyin: "néng", meaning: "poder (capacidad)" },
      { char: "那", pinyin: "nà", meaning: "ese / aquel" },
      { char: "看", pinyin: "kàn", meaning: "mirar / ver" },
      { char: "做", pinyin: "zuò", meaning: "hacer" },
      { char: "什", pinyin: "shén", meaning: "(en 什么) qué" },
      { char: "么", pinyin: "me", meaning: "(en 什么) partícula" },
      { char: "点", pinyin: "diǎn", meaning: "punto / un poco" },
      { char: "没", pinyin: "méi", meaning: "no (haber)" },
      { char: "大", pinyin: "dà", meaning: "grande" },
      { char: "下", pinyin: "xià", meaning: "abajo / bajar" },
      { char: "里", pinyin: "lǐ", meaning: "dentro" },
      { char: "现", pinyin: "xiàn", meaning: "actual / presente" },
      { char: "年", pinyin: "nián", meaning: "año" },
      { char: "多", pinyin: "duō", meaning: "mucho" },
      { char: "吗", pinyin: "ma", meaning: "partícula de pregunta" },
      { char: "出", pinyin: "chū", meaning: "salir" },
      { char: "太", pinyin: "tài", meaning: "demasiado" },
      { char: "果", pinyin: "guǒ", meaning: "fruta / resultado" },
      { char: "再", pinyin: "zài", meaning: "de nuevo / otra vez" },
      { char: "呢", pinyin: "ne", meaning: "partícula interrogativa" },
      { char: "小", pinyin: "xiǎo", meaning: "pequeño" },
      { char: "时", pinyin: "shí", meaning: "tiempo / hora" },
      { char: "候", pinyin: "hòu", meaning: "(en 时候) momento / esperar" },
      { char: "工", pinyin: "gōng", meaning: "trabajo" },
      { char: "作", pinyin: "zuò", meaning: "hacer / trabajo" },
      { char: "家", pinyin: "jiā", meaning: "casa / familia" },
      { char: "怎", pinyin: "zěn", meaning: "(en 怎么) cómo" },
      { char: "爱", pinyin: "ài", meaning: "amar" },
      { char: "开", pinyin: "kāi", meaning: "abrir" },
      { char: "喜", pinyin: "xǐ", meaning: "alegría / gustar" },
      { char: "欢", pinyin: "huān", meaning: "alegre / contento" },
      { char: "吃", pinyin: "chī", meaning: "comer" },
      { char: "谁", pinyin: "shéi", meaning: "quién" },
      { char: "今", pinyin: "jīn", meaning: "(en 今天) hoy" },
      { char: "天", pinyin: "tiān", meaning: "cielo / día" },
      { char: "觉", pinyin: "jué", meaning: "sentir / (睡觉) dormir" },
      { char: "月", pinyin: "yuè", meaning: "mes / luna" },
      { char: "认", pinyin: "rèn", meaning: "reconocer" },
      { char: "起", pinyin: "qǐ", meaning: "levantarse" },
      { char: "几", pinyin: "jǐ", meaning: "cuántos" },
      { char: "听", pinyin: "tīng", meaning: "escuchar" },
      { char: "叫", pinyin: "jiào", meaning: "llamar(se)" },
      { char: "生", pinyin: "shēng", meaning: "nacer / vida" },
      { char: "子", pinyin: "zǐ", meaning: "hijo / niño" },
      { char: "请", pinyin: "qǐng", meaning: "por favor / invitar" },
      { char: "钱", pinyin: "qián", meaning: "dinero" },
      { char: "本", pinyin: "běn", meaning: "clasificador (libros) / raíz" },
      { char: "回", pinyin: "huí", meaning: "regresar / vez" },
      { char: "东", pinyin: "dōng", meaning: "este (dirección)" },
      { char: "西", pinyin: "xī", meaning: "oeste / (东西) cosa" },
      { char: "三", pinyin: "sān", meaning: "tres" },
      { char: "样", pinyin: "yàng", meaning: "forma / tipo / así" },
      { char: "买", pinyin: "mǎi", meaning: "comprar" },
      { char: "后", pinyin: "hòu", meaning: "después / atrás" },
      { char: "老", pinyin: "lǎo", meaning: "viejo" },
      { char: "岁", pinyin: "suì", meaning: "años (de edad)" },
      { char: "朋", pinyin: "péng", meaning: "amigo" },
      { char: "友", pinyin: "yǒu", meaning: "amigo" },
      { char: "住", pinyin: "zhù", meaning: "vivir (residir)" },
      { char: "高", pinyin: "gāo", meaning: "alto" },
      { char: "先", pinyin: "xiān", meaning: "primero / antes" },
      { char: "关", pinyin: "guān", meaning: "cerrar / (关系) relación" },
      { char: "系", pinyin: "xì", meaning: "sistema / relación" },
      { char: "水", pinyin: "shuǐ", meaning: "agua" },
      { char: "写", pinyin: "xiě", meaning: "escribir" },
      { char: "国", pinyin: "guó", meaning: "país" },
      { char: "分", pinyin: "fēn", meaning: "dividir / minuto" },
      { char: "女", pinyin: "nǚ", meaning: "mujer" },
      { char: "机", pinyin: "jī", meaning: "máquina" },
      { char: "日", pinyin: "rì", meaning: "día / sol" },
      { char: "站", pinyin: "zhàn", meaning: "estar de pie / estación" },
      { char: "喝", pinyin: "hē", meaning: "beber" },
      { char: "学", pinyin: "xué", meaning: "estudiar" },
      { char: "校", pinyin: "xiào", meaning: "escuela" },
      { char: "坐", pinyin: "zuò", meaning: "sentarse" },
      { char: "识", pinyin: "shí", meaning: "conocer / reconocer" },
      { char: "钟", pinyin: "zhōng", meaning: "reloj / campana" },
      { char: "明", pinyin: "míng", meaning: "claro / brillante" },
      { char: "中", pinyin: "zhōng", meaning: "centro / medio" },
      { char: "四", pinyin: "sì", meaning: "cuatro" },
      { char: "块", pinyin: "kuài", meaning: "pedazo / (moneda) yuan" },
      { char: "谢", pinyin: "xiè", meaning: "agradecer" },
      { char: "前", pinyin: "qián", meaning: "adelante / antes" },
      { char: "少", pinyin: "shǎo", meaning: "poco" },
      { char: "妈", pinyin: "mā", meaning: "mamá" },
      { char: "电", pinyin: "diàn", meaning: "electricidad" },
      { char: "影", pinyin: "yǐng", meaning: "sombra / (电影) película" },
      { char: "哪", pinyin: "nǎ", meaning: "cuál" },
      { char: "昨", pinyin: "zuó", meaning: "ayer" },
      { char: "书", pinyin: "shū", meaning: "libro" },
      { char: "五", pinyin: "wǔ", meaning: "cinco" },
      { char: "同", pinyin: "tóng", meaning: "mismo / igual" },
      { char: "面", pinyin: "miàn", meaning: "cara / superficie / fideos" },
      { char: "医", pinyin: "yī", meaning: "médico / medicina" },
      { char: "院", pinyin: "yuàn", meaning: "patio / institución" },
      { char: "些", pinyin: "xiē", meaning: "algunos / unos" },
      { char: "狗", pinyin: "gǒu", meaning: "perro" },
      { char: "米", pinyin: "mǐ", meaning: "arroz / metro" },
      { char: "二", pinyin: "èr", meaning: "dos" },
      { char: "儿", pinyin: "ér", meaning: "hijo / niño (儿子)" },
      { char: "视", pinyin: "shì", meaning: "ver / visión (电视)" },
      { char: "午", pinyin: "wǔ", meaning: "mediodía" },
      { char: "习", pinyin: "xí", meaning: "practicar" },
      { char: "师", pinyin: "shī", meaning: "maestro" },
      { char: "六", pinyin: "liù", meaning: "seis" },
      { char: "名", pinyin: "míng", meaning: "nombre" },
      { char: "字", pinyin: "zì", meaning: "carácter / letra" },
      { char: "十", pinyin: "shí", meaning: "diez" },
      { char: "见", pinyin: "jiàn", meaning: "ver / encontrarse con" },
      { char: "话", pinyin: "huà", meaning: "palabra / habla" },
      { char: "说", pinyin: "shuō", meaning: "decir" },
      { char: "爸", pinyin: "bà", meaning: "papá" },
      { char: "漂", pinyin: "piào", meaning: "(漂亮) bonito" },
      { char: "亮", pinyin: "liàng", meaning: "brillante / (漂亮) bonito" },
      { char: "兴", pinyin: "xìng", meaning: "ánimo / interés (高兴)" },
      { char: "热", pinyin: "rè", meaning: "caliente" },
      { char: "睡", pinyin: "shuì", meaning: "dormir" },
      { char: "脑", pinyin: "nǎo", meaning: "cerebro (电脑)" },
      { char: "读", pinyin: "dú", meaning: "leer" },
      { char: "冷", pinyin: "lěng", meaning: "frío" },
      { char: "飞", pinyin: "fēi", meaning: "volar" },
      { char: "客", pinyin: "kè", meaning: "huésped / cliente" },
      { char: "猫", pinyin: "māo", meaning: "gato" },
      { char: "火", pinyin: "huǒ", meaning: "fuego" },
      { char: "打", pinyin: "dǎ", meaning: "golpear / hacer (llamada)" },
      { char: "喂", pinyin: "wèi", meaning: "¡oye! / (al teléfono) hola" },
      { char: "期", pinyin: "qī", meaning: "período (星期)" },
      { char: "八", pinyin: "bā", meaning: "ocho" },
      { char: "七", pinyin: "qī", meaning: "siete" },
      { char: "菜", pinyin: "cài", meaning: "verdura / platillo" },
      { char: "星", pinyin: "xīng", meaning: "estrella" },
      { char: "衣", pinyin: "yī", meaning: "ropa" },
      { char: "服", pinyin: "fú", meaning: "ropa / servir" },
      { char: "姐", pinyin: "jiě", meaning: "hermana mayor" },
      { char: "气", pinyin: "qì", meaning: "aire / energía" },
      { char: "茶", pinyin: "chá", meaning: "té" },
      { char: "语", pinyin: "yǔ", meaning: "idioma / lengua" },
      { char: "九", pinyin: "jiǔ", meaning: "nueve" },
      { char: "商", pinyin: "shāng", meaning: "comercio (商店)" },
      { char: "租", pinyin: "zū", meaning: "alquilar" },
      { char: "苹", pinyin: "píng", meaning: "(苹果) manzana" },
      { char: "车", pinyin: "chē", meaning: "carro / vehículo" },
      { char: "店", pinyin: "diàn", meaning: "tienda" },
      { char: "零", pinyin: "líng", meaning: "cero" },
      { char: "桌", pinyin: "zhuō", meaning: "mesa" },
      { char: "馆", pinyin: "guǎn", meaning: "edificio / establecimiento" },
      { char: "椅", pinyin: "yǐ", meaning: "silla" },
      { char: "北", pinyin: "běi", meaning: "norte" },
      { char: "京", pinyin: "jīng", meaning: "capital (北京)" },
      { char: "雨", pinyin: "yǔ", meaning: "lluvia" },
      { char: "杯", pinyin: "bēi", meaning: "vaso / taza" },
      { char: "饭", pinyin: "fàn", meaning: "comida / arroz cocido" },
      { char: "汉", pinyin: "hàn", meaning: "(etnia) han / (汉语) chino" },
    ]
  },
  {
    id: 2,
    name: "Nivel 2 · HSK 2 (Elemental)",
    chars: [
      { char: "就", pinyin: "jiù", meaning: "entonces / precisamente" },
      { char: "要", pinyin: "yào", meaning: "querer / necesitar" },
      { char: "也", pinyin: "yě", meaning: "también" },
      { char: "到", pinyin: "dào", meaning: "llegar" },
      { char: "还", pinyin: "hái", meaning: "todavía / además" },
      { char: "着", pinyin: "zhe", meaning: "partícula de acción continua" },
      { char: "给", pinyin: "gěi", meaning: "dar / para" },
      { char: "让", pinyin: "ràng", meaning: "dejar / permitir" },
      { char: "自", pinyin: "zì", meaning: "uno mismo" },
      { char: "吧", pinyin: "ba", meaning: "partícula de sugerencia" },
      { char: "得", pinyin: "de", meaning: "partícula de grado (跑得快)" },
      { char: "可", pinyin: "kě", meaning: "poder / (可以) permitir" },
      { char: "以", pinyin: "yǐ", meaning: "con / (可以)" },
      { char: "为", pinyin: "wèi", meaning: "para / por" },
      { char: "从", pinyin: "cóng", meaning: "desde" },
      { char: "真", pinyin: "zhēn", meaning: "verdadero / de verdad" },
      { char: "两", pinyin: "liǎng", meaning: "dos (cantidad)" },
      { char: "已", pinyin: "yǐ", meaning: "ya (已经)" },
      { char: "经", pinyin: "jīng", meaning: "pasar por / (经济) economía" },
      { char: "最", pinyin: "zuì", meaning: "el más" },
      { char: "因", pinyin: "yīn", meaning: "causa (因为)" },
      { char: "次", pinyin: "cì", meaning: "vez / clasificador de veces" },
      { char: "知", pinyin: "zhī", meaning: "saber" },
      { char: "道", pinyin: "dào", meaning: "camino / decir" },
      { char: "题", pinyin: "tí", meaning: "pregunta / tema" },
      { char: "问", pinyin: "wèn", meaning: "preguntar" },
      { char: "走", pinyin: "zǒu", meaning: "caminar" },
      { char: "它", pinyin: "tā", meaning: "eso (animal/cosa)" },
      { char: "但", pinyin: "dàn", meaning: "pero" },
      { char: "间", pinyin: "jiān", meaning: "intervalo / espacio" },
      { char: "始", pinyin: "shǐ", meaning: "comenzar (开始)" },
      { char: "新", pinyin: "xīn", meaning: "nuevo" },
      { char: "找", pinyin: "zhǎo", meaning: "buscar" },
      { char: "快", pinyin: "kuài", meaning: "rápido" },
      { char: "比", pinyin: "bǐ", meaning: "comparar" },
      { char: "所", pinyin: "suǒ", meaning: "lugar / lo que" },
      { char: "向", pinyin: "xiàng", meaning: "hacia" },
      { char: "希", pinyin: "xī", meaning: "esperar (希望)" },
      { char: "望", pinyin: "wàng", meaning: "esperar / mirar a lo lejos" },
      { char: "非", pinyin: "fēi", meaning: "no / (非常) muy" },
      { char: "常", pinyin: "cháng", meaning: "a menudo / normal" },
      { char: "孩", pinyin: "hái", meaning: "niño (孩子)" },
      { char: "别", pinyin: "bié", meaning: "no (imperativo) / otro" },
      { char: "公", pinyin: "gōng", meaning: "público" },
      { char: "司", pinyin: "sī", meaning: "gestionar / compañía" },
      { char: "第", pinyin: "dì", meaning: "prefijo ordinal" },
      { char: "情", pinyin: "qíng", meaning: "sentimiento / situación" },
      { char: "长", pinyin: "cháng", meaning: "largo / zhǎng crecer" },
      { char: "告", pinyin: "gào", meaning: "avisar (告诉)" },
      { char: "诉", pinyin: "sù", meaning: "contar / quejarse" },
      { char: "事", pinyin: "shì", meaning: "asunto" },
      { char: "行", pinyin: "xíng", meaning: "caminar / estar bien" },
      { char: "号", pinyin: "hào", meaning: "número / fecha" },
      { char: "场", pinyin: "chǎng", meaning: "lugar / campo" },
      { char: "件", pinyin: "jiàn", meaning: "clasificador de objetos" },
      { char: "正", pinyin: "zhèng", meaning: "correcto / justo" },
      { char: "进", pinyin: "jìn", meaning: "entrar" },
      { char: "张", pinyin: "zhāng", meaning: "clasificador plano / abrir" },
      { char: "准", pinyin: "zhǔn", meaning: "permitir / preciso (准备)" },
      { char: "备", pinyin: "bèi", meaning: "preparar" },
      { char: "每", pinyin: "měi", meaning: "cada" },
      { char: "您", pinyin: "nín", meaning: "usted (cortés)" },
      { char: "送", pinyin: "sòng", meaning: "enviar / regalar" },
      { char: "笑", pinyin: "xiào", meaning: "reír / sonreír" },
      { char: "完", pinyin: "wán", meaning: "terminar" },
      { char: "路", pinyin: "lù", meaning: "camino" },
      { char: "男", pinyin: "nán", meaning: "hombre" },
      { char: "玩", pinyin: "wán", meaning: "jugar" },
      { char: "门", pinyin: "mén", meaning: "puerta" },
      { char: "穿", pinyin: "chuān", meaning: "vestir / atravesar" },
      { char: "息", pinyin: "xī", meaning: "descansar / (消息) noticia" },
      { char: "表", pinyin: "biǎo", meaning: "reloj (de pulsera) / expresar" },
      { char: "外", pinyin: "wài", meaning: "fuera" },
      { char: "帮", pinyin: "bāng", meaning: "ayudar" },
      { char: "助", pinyin: "zhù", meaning: "ayudar" },
      { char: "晚", pinyin: "wǎn", meaning: "tarde / noche" },
      { char: "错", pinyin: "cuò", meaning: "error / equivocado" },
      { char: "意", pinyin: "yì", meaning: "significado / intención" },
      { char: "离", pinyin: "lí", meaning: "alejarse de / distancia" },
      { char: "卖", pinyin: "mài", meaning: "vender" },
      { char: "远", pinyin: "yuǎn", meaning: "lejos" },
      { char: "游", pinyin: "yóu", meaning: "nadar / viajar" },
      { char: "动", pinyin: "dòng", meaning: "mover" },
      { char: "考", pinyin: "kǎo", meaning: "examinar" },
      { char: "近", pinyin: "jìn", meaning: "cerca" },
      { char: "乐", pinyin: "lè", meaning: "feliz / (yuè) música" },
      { char: "务", pinyin: "wù", meaning: "asunto (服务)" },
      { char: "懂", pinyin: "dǒng", meaning: "entender" },
      { char: "员", pinyin: "yuán", meaning: "miembro / empleado" },
      { char: "白", pinyin: "bái", meaning: "blanco" },
      { char: "报", pinyin: "bào", meaning: "informar / periódico" },
      { char: "药", pinyin: "yào", meaning: "medicina" },
      { char: "黑", pinyin: "hēi", meaning: "negro" },
      { char: "身", pinyin: "shēn", meaning: "cuerpo" },
      { char: "体", pinyin: "tǐ", meaning: "cuerpo" },
      { char: "元", pinyin: "yuán", meaning: "unidad monetaria / yuan" },
      { char: "介", pinyin: "jiè", meaning: "presentar (介绍)" },
      { char: "绍", pinyin: "shào", meaning: "(介绍) presentar" },
      { char: "红", pinyin: "hóng", meaning: "rojo" },
      { char: "迎", pinyin: "yíng", meaning: "recibir / dar la bienvenida" },
      { char: "便", pinyin: "biàn", meaning: "conveniente / entonces" },
      { char: "眼", pinyin: "yǎn", meaning: "ojo" },
      { char: "睛", pinyin: "jīng", meaning: "(眼睛) ojo" },
      { char: "手", pinyin: "shǒu", meaning: "mano" },
      { char: "忙", pinyin: "máng", meaning: "ocupado" },
      { char: "试", pinyin: "shì", meaning: "probar / examen" },
      { char: "票", pinyin: "piào", meaning: "boleto" },
      { char: "教", pinyin: "jiào", meaning: "enseñar" },
      { char: "思", pinyin: "sī", meaning: "pensar (意思)" },
      { char: "弟", pinyin: "dì", meaning: "hermano menor" },
      { char: "早", pinyin: "zǎo", meaning: "temprano" },
      { char: "答", pinyin: "dá", meaning: "responder" },
      { char: "运", pinyin: "yùn", meaning: "transportar / suerte" },
      { char: "室", pinyin: "shì", meaning: "habitación" },
      { char: "妻", pinyin: "qī", meaning: "esposa" },
      { char: "鱼", pinyin: "yú", meaning: "pescado" },
      { char: "累", pinyin: "lèi", meaning: "cansado" },
      { char: "休", pinyin: "xiū", meaning: "descansar" },
      { char: "班", pinyin: "bān", meaning: "clase / turno" },
      { char: "边", pinyin: "biān", meaning: "lado" },
      { char: "洗", pinyin: "xǐ", meaning: "lavar" },
      { char: "船", pinyin: "chuán", meaning: "barco" },
      { char: "右", pinyin: "yòu", meaning: "derecha" },
      { char: "左", pinyin: "zuǒ", meaning: "izquierda" },
      { char: "房", pinyin: "fáng", meaning: "habitación / casa" },
      { char: "丈", pinyin: "zhàng", meaning: "(丈夫) esposo" },
      { char: "夫", pinyin: "fū", meaning: "esposo / hombre" },
      { char: "课", pinyin: "kè", meaning: "clase / lección" },
      { char: "共", pinyin: "gòng", meaning: "en total / junto" },
      { char: "哥", pinyin: "gē", meaning: "hermano mayor" },
      { char: "色", pinyin: "sè", meaning: "color" },
      { char: "咖", pinyin: "kā", meaning: "(咖啡) café" },
      { char: "啡", pinyin: "fēi", meaning: "(咖啡) café" },
      { char: "千", pinyin: "qiān", meaning: "mil" },
      { char: "慢", pinyin: "màn", meaning: "lento" },
      { char: "旁", pinyin: "páng", meaning: "al lado" },
      { char: "颜", pinyin: "yán", meaning: "color (颜色)" },
      { char: "球", pinyin: "qiú", meaning: "pelota" },
      { char: "雪", pinyin: "xuě", meaning: "nieve" },
      { char: "妹", pinyin: "mèi", meaning: "hermana menor" },
      { char: "病", pinyin: "bìng", meaning: "enfermedad" },
      { char: "纸", pinyin: "zhǐ", meaning: "papel" },
      { char: "贵", pinyin: "guì", meaning: "caro / honorable" },
      { char: "踢", pinyin: "tī", meaning: "patear" },
      { char: "步", pinyin: "bù", meaning: "paso" },
      { char: "百", pinyin: "bǎi", meaning: "cien" },
      { char: "旅", pinyin: "lǚ", meaning: "viajar" },
      { char: "床", pinyin: "chuáng", meaning: "cama" },
      { char: "蛋", pinyin: "dàn", meaning: "huevo" },
      { char: "舞", pinyin: "wǔ", meaning: "bailar" },
      { char: "奶", pinyin: "nǎi", meaning: "leche" },
      { char: "宜", pinyin: "yí", meaning: "adecuado (便宜)" },
      { char: "唱", pinyin: "chàng", meaning: "cantar" },
      { char: "歌", pinyin: "gē", meaning: "canción" },
      { char: "牛", pinyin: "niú", meaning: "vaca / buey" },
      { char: "鸡", pinyin: "jī", meaning: "pollo" },
      { char: "肉", pinyin: "ròu", meaning: "carne" },
      { char: "姓", pinyin: "xìng", meaning: "apellido" },
      { char: "泳", pinyin: "yǒng", meaning: "nadar (游泳)" },
      { char: "跳", pinyin: "tiào", meaning: "saltar" },
      { char: "阴", pinyin: "yīn", meaning: "nublado / yin" },
      { char: "斤", pinyin: "jīn", meaning: "medio kilo (unidad)" },
      { char: "汽", pinyin: "qì", meaning: "vapor (汽车)" },
      { char: "跑", pinyin: "pǎo", meaning: "correr" },
      { char: "瓜", pinyin: "guā", meaning: "melón" },
      { char: "晴", pinyin: "qíng", meaning: "despejado (clima)" },
      { char: "羊", pinyin: "yáng", meaning: "oveja" },
      { char: "篮", pinyin: "lán", meaning: "canasta (篮球)" },
    ]
  },
  {
    id: 3,
    name: "Nivel 3 · HSK 3 (Intermedio)",
    chars: [
      { char: "啊", pinyin: "a", meaning: "partícula exclamativa" },
      { char: "把", pinyin: "bǎ", meaning: "partícula (marca objeto) / agarrar" },
      { char: "被", pinyin: "bèi", meaning: "partícula pasiva / por" },
      { char: "己", pinyin: "jǐ", meaning: "uno mismo (自己)" },
      { char: "过", pinyin: "guò", meaning: "pasar / partícula de experiencia" },
      { char: "而", pinyin: "ér", meaning: "y / pero (conjunción)" },
      { char: "用", pinyin: "yòng", meaning: "usar" },
      { char: "如", pinyin: "rú", meaning: "como / si" },
      { char: "又", pinyin: "yòu", meaning: "de nuevo / además" },
      { char: "只", pinyin: "zhǐ", meaning: "solo / solamente" },
      { char: "更", pinyin: "gèng", meaning: "más (comparativo)" },
      { char: "需", pinyin: "xū", meaning: "necesitar (需要)" },
      { char: "地", pinyin: "de", meaning: "partícula adverbial / (dì) tierra" },
      { char: "才", pinyin: "cái", meaning: "solo entonces / talento" },
      { char: "跟", pinyin: "gēn", meaning: "seguir / con" },
      { char: "像", pinyin: "xiàng", meaning: "parecerse a" },
      { char: "当", pinyin: "dāng", meaning: "cuando / servir como" },
      { char: "应", pinyin: "yīng", meaning: "deber / responder" },
      { char: "该", pinyin: "gāi", meaning: "deber (debería)" },
      { char: "带", pinyin: "dài", meaning: "llevar / cinturón" },
      { char: "位", pinyin: "wèi", meaning: "posición / clasificador (personas)" },
      { char: "种", pinyin: "zhǒng", meaning: "tipo / semilla" },
      { char: "发", pinyin: "fā", meaning: "enviar / desarrollar" },
      { char: "定", pinyin: "dìng", meaning: "fijar / determinar" },
      { char: "直", pinyin: "zhí", meaning: "recto / directo" },
      { char: "世", pinyin: "shì", meaning: "mundo / generación" },
      { char: "界", pinyin: "jiè", meaning: "límite / (世界) mundo" },
      { char: "且", pinyin: "qiě", meaning: "además" },
      { char: "重", pinyin: "zhòng", meaning: "pesado / importante" },
      { char: "必", pinyin: "bì", meaning: "necesariamente" },
      { char: "须", pinyin: "xū", meaning: "deber / necesitar" },
      { char: "方", pinyin: "fāng", meaning: "dirección / cuadrado" },
      { char: "成", pinyin: "chéng", meaning: "convertirse en / lograr" },
      { char: "其", pinyin: "qí", meaning: "su / eso" },
      { char: "感", pinyin: "gǎn", meaning: "sentir" },
      { char: "赛", pinyin: "sài", meaning: "competencia" },
      { char: "然", pinyin: "rán", meaning: "así (然后 / 虽然)" },
      { char: "担", pinyin: "dān", meaning: "cargar (担心)" },
      { char: "心", pinyin: "xīn", meaning: "corazón" },
      { char: "条", pinyin: "tiáo", meaning: "clasificador (alargado) / tira" },
      { char: "放", pinyin: "fàng", meaning: "poner / soltar" },
      { char: "拿", pinyin: "ná", meaning: "tomar / agarrar" },
      { char: "解", pinyin: "jiě", meaning: "resolver / desatar (解决)" },
      { char: "通", pinyin: "tōng", meaning: "pasar por / comunicar" },
      { char: "参", pinyin: "cān", meaning: "participar (参加)" },
      { char: "加", pinyin: "jiā", meaning: "agregar / sumar" },
      { char: "安", pinyin: "ān", meaning: "paz / seguro" },
      { char: "结", pinyin: "jié", meaning: "anudar / concluir" },
      { char: "决", pinyin: "jué", meaning: "decidir" },
      { char: "选", pinyin: "xuǎn", meaning: "elegir" },
      { char: "择", pinyin: "zé", meaning: "escoger" },
      { char: "或", pinyin: "huò", meaning: "o / quizás" },
      { char: "者", pinyin: "zhě", meaning: "el que (persona que)" },
      { char: "使", pinyin: "shǐ", meaning: "hacer que / usar" },
      { char: "实", pinyin: "shí", meaning: "real / verdadero" },
      { char: "求", pinyin: "qiú", meaning: "pedir / buscar" },
      { char: "信", pinyin: "xìn", meaning: "carta / creer" },
      { char: "接", pinyin: "jiē", meaning: "recibir / conectar" },
      { char: "相", pinyin: "xiāng", meaning: "mutuamente / (xiàng) aspecto" },
      { char: "花", pinyin: "huā", meaning: "flor / gastar" },
      { char: "虽", pinyin: "suī", meaning: "aunque" },
      { char: "干", pinyin: "gàn", meaning: "hacer / (gān) seco" },
      { char: "于", pinyin: "yú", meaning: "en / a (preposición)" },
      { char: "束", pinyin: "shù", meaning: "atar / manojo (结束)" },
      { char: "努", pinyin: "nǔ", meaning: "esforzarse (努力)" },
      { char: "力", pinyin: "lì", meaning: "fuerza" },
      { char: "查", pinyin: "chá", meaning: "revisar / investigar" },
      { char: "调", pinyin: "tiáo", meaning: "ajustar / (diào) tono" },
      { char: "理", pinyin: "lǐ", meaning: "razón / organizar (道理)" },
      { char: "护", pinyin: "hù", meaning: "proteger" },
      { char: "办", pinyin: "bàn", meaning: "hacer / manejar" },
      { char: "法", pinyin: "fǎ", meaning: "ley / método" },
      { char: "特", pinyin: "tè", meaning: "especial" },
      { char: "难", pinyin: "nán", meaning: "difícil" },
      { char: "注", pinyin: "zhù", meaning: "anotar / prestar (注意)" },
      { char: "变", pinyin: "biàn", meaning: "cambiar" },
      { char: "讲", pinyin: "jiǎng", meaning: "hablar / explicar" },
      { char: "万", pinyin: "wàn", meaning: "diez mil" },
      { char: "片", pinyin: "piàn", meaning: "trozo / clasificador plano" },
      { char: "越", pinyin: "yuè", meaning: "cuanto más (越来越)" },
      { char: "根", pinyin: "gēn", meaning: "raíz / clasificador (alargado)" },
      { char: "市", pinyin: "shì", meaning: "mercado / ciudad" },
      { char: "城", pinyin: "chéng", meaning: "ciudad (muro)" },
      { char: "响", pinyin: "xiǎng", meaning: "sonar / sonido" },
      { char: "目", pinyin: "mù", meaning: "ojo / objetivo (目的)" },
      { char: "戏", pinyin: "xì", meaning: "juego / obra (游戏)" },
      { char: "马", pinyin: "mǎ", meaning: "caballo" },
      { char: "较", pinyin: "jiào", meaning: "comparar (比较)" },
      { char: "换", pinyin: "huàn", meaning: "cambiar (intercambiar)" },
      { char: "提", pinyin: "tí", meaning: "levantar / mencionar" },
      { char: "终", pinyin: "zhōng", meaning: "final (最终)" },
      { char: "脸", pinyin: "liǎn", meaning: "cara" },
      { char: "口", pinyin: "kǒu", meaning: "boca" },
      { char: "除", pinyin: "chú", meaning: "excepto / quitar" },
      { char: "总", pinyin: "zǒng", meaning: "siempre / en total" },
      { char: "双", pinyin: "shuāng", meaning: "par / clasificador (pares)" },
      { char: "突", pinyin: "tū", meaning: "repentino (突然)" },
      { char: "段", pinyin: "duàn", meaning: "segmento / clasificador" },
      { char: "检", pinyin: "jiǎn", meaning: "revisar (检查)" },
      { char: "容", pinyin: "róng", meaning: "contener / permitir (容易)" },
      { char: "易", pinyin: "yì", meaning: "fácil" },
      { char: "据", pinyin: "jù", meaning: "según / evidencia" },
      { char: "算", pinyin: "suàn", meaning: "calcular / contar" },
      { char: "记", pinyin: "jì", meaning: "recordar / anotar" },
      { char: "辆", pinyin: "liàng", meaning: "clasificador (vehículos)" },
      { char: "刚", pinyin: "gāng", meaning: "hace poco / justo" },
      { char: "单", pinyin: "dān", meaning: "simple / único" },
      { char: "简", pinyin: "jiǎn", meaning: "simple (简单)" },
      { char: "半", pinyin: "bàn", meaning: "mitad" },
      { char: "愿", pinyin: "yuàn", meaning: "desear / dispuesto" },
      { char: "音", pinyin: "yīn", meaning: "sonido" },
      { char: "包", pinyin: "bāo", meaning: "bolsa / envolver" },
      { char: "楼", pinyin: "lóu", meaning: "edificio / piso" },
      { char: "照", pinyin: "zhào", meaning: "fotografiar / iluminar" },
      { char: "清", pinyin: "qīng", meaning: "claro (清楚)" },
      { char: "楚", pinyin: "chǔ", meaning: "claro (清楚)" },
      { char: "银", pinyin: "yín", meaning: "plata" },
      { char: "故", pinyin: "gù", meaning: "razón / historia (故事)" },
      { char: "议", pinyin: "yì", meaning: "discutir" },
      { char: "般", pinyin: "bān", meaning: "tipo (一般)" },
      { char: "闻", pinyin: "wén", meaning: "oler / noticia (新闻)" },
      { char: "声", pinyin: "shēng", meaning: "sonido / voz" },
      { char: "数", pinyin: "shù", meaning: "número" },
      { char: "示", pinyin: "shì", meaning: "mostrar (表示)" },
      { char: "历", pinyin: "lì", meaning: "pasar / historia (历史)" },
      { char: "史", pinyin: "shǐ", meaning: "historia" },
      { char: "哭", pinyin: "kū", meaning: "llorar" },
      { char: "敢", pinyin: "gǎn", meaning: "atreverse" },
      { char: "低", pinyin: "dī", meaning: "bajo" },
      { char: "节", pinyin: "jié", meaning: "festival / sección" },
      { char: "健", pinyin: "jiàn", meaning: "saludable (健康)" },
      { char: "康", pinyin: "kāng", meaning: "salud (健康)" },
      { char: "满", pinyin: "mǎn", meaning: "lleno" },
      { char: "差", pinyin: "chà", meaning: "faltar / diferencia" },
      { char: "婚", pinyin: "hūn", meaning: "matrimonio" },
      { char: "短", pinyin: "duǎn", meaning: "corto" },
      { char: "练", pinyin: "liàn", meaning: "entrenar" },
      { char: "乎", pinyin: "hū", meaning: "(几乎) casi" },
      { char: "附", pinyin: "fù", meaning: "adjuntar / cercano" },
      { char: "脚", pinyin: "jiǎo", meaning: "pie" },
      { char: "主", pinyin: "zhǔ", meaning: "principal / dueño" },
      { char: "超", pinyin: "chāo", meaning: "superar / super-" },
      { char: "遇", pinyin: "yù", meaning: "encontrarse con" },
      { char: "居", pinyin: "jū", meaning: "vivir / residir" },
      { char: "轻", pinyin: "qīng", meaning: "ligero" },
      { char: "久", pinyin: "jiǔ", meaning: "mucho tiempo" },
      { char: "画", pinyin: "huà", meaning: "dibujar / pintura" },
      { char: "演", pinyin: "yǎn", meaning: "actuar" },
      { char: "业", pinyin: "yè", meaning: "profesión / industria" },
      { char: "环", pinyin: "huán", meaning: "anillo / (环境) entorno" },
      { char: "境", pinyin: "jìng", meaning: "entorno / territorio" },
      { char: "板", pinyin: "bǎn", meaning: "tabla" },
      { char: "育", pinyin: "yù", meaning: "educar" },
      { char: "祝", pinyin: "zhù", meaning: "desear / felicitar" },
      { char: "层", pinyin: "céng", meaning: "piso / capa" },
      { char: "腿", pinyin: "tuǐ", meaning: "pierna" },
      { char: "复", pinyin: "fù", meaning: "repetir / recuperar" },
      { char: "坏", pinyin: "huài", meaning: "malo / roto" },
      { char: "鞋", pinyin: "xié", meaning: "zapato" },
      { char: "惯", pinyin: "guàn", meaning: "hábito" },
      { char: "化", pinyin: "huà", meaning: "transformar / cambiar" },
      { char: "周", pinyin: "zhōu", meaning: "semana" },
      { char: "末", pinyin: "mò", meaning: "final (周末)" },
      { char: "空", pinyin: "kōng", meaning: "vacío / cielo" },
      { char: "忘", pinyin: "wàng", meaning: "olvidar" },
      { char: "文", pinyin: "wén", meaning: "escritura / cultura" },
      { char: "极", pinyin: "jí", meaning: "extremo / muy" },
      { char: "物", pinyin: "wù", meaning: "cosa / objeto" },
      { char: "举", pinyin: "jǔ", meaning: "levantar" },
      { char: "网", pinyin: "wǎng", meaning: "red" },
      { char: "饿", pinyin: "è", meaning: "tener hambre" },
      { char: "树", pinyin: "shù", meaning: "árbol" },
      { char: "平", pinyin: "píng", meaning: "plano / ordinario" },
      { char: "借", pinyin: "jiè", meaning: "prestar / pedir prestado" },
      { char: "头", pinyin: "tóu", meaning: "cabeza" },
      { char: "害", pinyin: "hài", meaning: "daño / perjudicar" },
      { char: "怕", pinyin: "pà", meaning: "temer / tener miedo" },
      { char: "级", pinyin: "jí", meaning: "grado / nivel" },
      { char: "鸟", pinyin: "niǎo", meaning: "pájaro" },
      { char: "蓝", pinyin: "lán", meaning: "azul" },
      { char: "顾", pinyin: "gù", meaning: "cuidar / atender (顾客)" },
      { char: "疼", pinyin: "téng", meaning: "doler" },
      { char: "奇", pinyin: "qí", meaning: "extraño / raro" },
      { char: "怪", pinyin: "guài", meaning: "extraño / culpar" },
      { char: "角", pinyin: "jiǎo", meaning: "esquina / cuerno" },
      { char: "礼", pinyin: "lǐ", meaning: "regalo / cortesía" },
      { char: "刻", pinyin: "kè", meaning: "momento / grabar" },
      { char: "南", pinyin: "nán", meaning: "sur" },
      { char: "旧", pinyin: "jiù", meaning: "viejo (objeto)" },
      { char: "黄", pinyin: "huáng", meaning: "amarillo" },
      { char: "趣", pinyin: "qù", meaning: "interés (兴趣)" },
      { char: "绩", pinyin: "jì", meaning: "logro (成绩)" },
      { char: "聪", pinyin: "cōng", meaning: "inteligente (聪明)" },
      { char: "香", pinyin: "xiāng", meaning: "aromático" },
      { char: "灯", pinyin: "dēng", meaning: "lámpara" },
      { char: "阳", pinyin: "yáng", meaning: "sol (太阳)" },
      { char: "糖", pinyin: "táng", meaning: "azúcar / dulce" },
      { char: "急", pinyin: "jí", meaning: "urgente / ansioso" },
      { char: "园", pinyin: "yuán", meaning: "jardín / parque" },
      { char: "骑", pinyin: "qí", meaning: "montar (bicicleta)" },
      { char: "河", pinyin: "hé", meaning: "río" },
      { char: "搬", pinyin: "bān", meaning: "mudarse / mover" },
      { char: "舒", pinyin: "shū", meaning: "cómodo (舒服)" },
      { char: "胖", pinyin: "pàng", meaning: "gordo" },
      { char: "典", pinyin: "diǎn", meaning: "diccionario (词典)" },
      { char: "净", pinyin: "jìng", meaning: "limpio (干净)" },
      { char: "草", pinyin: "cǎo", meaning: "hierba" },
      { char: "甜", pinyin: "tián", meaning: "dulce" },
      { char: "静", pinyin: "jìng", meaning: "tranquilo (安静)" },
      { char: "图", pinyin: "tú", meaning: "imagen / mapa" },
      { char: "镜", pinyin: "jìng", meaning: "espejo / lente" },
      { char: "瘦", pinyin: "shòu", meaning: "delgado" },
      { char: "绿", pinyin: "lǜ", meaning: "verde" },
      { char: "啤", pinyin: "pí", meaning: "(啤酒) cerveza" },
      { char: "酒", pinyin: "jiǔ", meaning: "alcohol / licor" },
      { char: "糕", pinyin: "gāo", meaning: "pastel" },
      { char: "鲜", pinyin: "xiān", meaning: "fresco" },
      { char: "碗", pinyin: "wǎn", meaning: "tazón" },
      { char: "铁", pinyin: "tiě", meaning: "hierro / metal" },
      { char: "刷", pinyin: "shuā", meaning: "cepillar" },
      { char: "厨", pinyin: "chú", meaning: "cocina (厨房)" },
      { char: "爷", pinyin: "yé", meaning: "abuelo (爷爷)" },
      { char: "云", pinyin: "yún", meaning: "nube" },
      { char: "邻", pinyin: "lín", meaning: "vecino" },
      { char: "渴", pinyin: "kě", meaning: "tener sed" },
      { char: "耳", pinyin: "ěr", meaning: "oreja" },
      { char: "朵", pinyin: "duǒ", meaning: "clasificador (flores)" },
      { char: "鼻", pinyin: "bí", meaning: "nariz" },
      { char: "叔", pinyin: "shū", meaning: "tío" },
      { char: "澡", pinyin: "zǎo", meaning: "baño (洗澡)" },
      { char: "帽", pinyin: "mào", meaning: "sombrero" },
      { char: "街", pinyin: "jiē", meaning: "calle" },
      { char: "冒", pinyin: "mào", meaning: "emitir / arriesgar (感冒)" },
      { char: "迟", pinyin: "chí", meaning: "tarde / retrasado" },
      { char: "锻", pinyin: "duàn", meaning: "forjar (锻炼)" },
      { char: "炼", pinyin: "liàn", meaning: "forjar / entrenar (锻炼)" },
      { char: "裤", pinyin: "kù", meaning: "pantalón" },
      { char: "夏", pinyin: "xià", meaning: "verano" },
      { char: "梯", pinyin: "tī", meaning: "escalera" },
      { char: "刮", pinyin: "guā", meaning: "soplar (viento)" },
      { char: "笔", pinyin: "bǐ", meaning: "pluma / lápiz" },
      { char: "矮", pinyin: "ǎi", meaning: "bajo (estatura)" },
      { char: "春", pinyin: "chūn", meaning: "primavera" },
      { char: "冰", pinyin: "bīng", meaning: "hielo" },
      { char: "箱", pinyin: "xiāng", meaning: "caja / baúl" },
      { char: "阿", pinyin: "ā", meaning: "(阿姨) tía" },
      { char: "姨", pinyin: "yí", meaning: "tía" },
      { char: "烧", pinyin: "shāo", meaning: "quemar / cocinar" },
      { char: "季", pinyin: "jì", meaning: "estación (del año)" },
      { char: "饱", pinyin: "bǎo", meaning: "lleno / saciado" },
      { char: "衬", pinyin: "chèn", meaning: "(衬衫) camisa" },
      { char: "衫", pinyin: "shān", meaning: "camisa" },
      { char: "宾", pinyin: "bīn", meaning: "huésped" },
      { char: "冬", pinyin: "dōng", meaning: "invierno" },
      { char: "裙", pinyin: "qún", meaning: "falda" },
      { char: "蕉", pinyin: "jiāo", meaning: "(香蕉) plátano" },
      { char: "秋", pinyin: "qiū", meaning: "otoño" },
      { char: "普", pinyin: "pǔ", meaning: "común (普通)" },
      { char: "伞", pinyin: "sǎn", meaning: "paraguas" },
      { char: "扫", pinyin: "sǎo", meaning: "barrer" },
      { char: "葡", pinyin: "pú", meaning: "(葡萄) uva" },
      { char: "萄", pinyin: "táo", meaning: "(葡萄) uva" },
      { char: "熊", pinyin: "xióng", meaning: "oso" },
      { char: "汁", pinyin: "zhī", meaning: "jugo" },
      { char: "盘", pinyin: "pán", meaning: "plato" },
      { char: "铅", pinyin: "qiān", meaning: "plomo (铅笔)" },
      { char: "词", pinyin: "cí", meaning: "palabra" },
      { char: "句", pinyin: "jù", meaning: "oración / frase" },
      { char: "筷", pinyin: "kuài", meaning: "palillos" },
      { char: "爬", pinyin: "pá", meaning: "trepar / gatear" },
      { char: "山", pinyin: "shān", meaning: "montaña" },
      { char: "李", pinyin: "lǐ", meaning: "ciruela / apellido Li" },
    ]
  },
  {
    id: 4,
    name: "Nivel 4 · HSK 4 (Avanzado)",
    chars: [
      { char: "等", pinyin: "děng", meaning: "esperar / etcétera" },
      { char: "与", pinyin: "yǔ", meaning: "y / con" },
      { char: "之", pinyin: "zhī", meaning: "partícula posesiva clásica (de)" },
      { char: "死", pinyin: "sǐ", meaning: "morir" },
      { char: "却", pinyin: "què", meaning: "sin embargo" },
      { char: "活", pinyin: "huó", meaning: "vivir" },
      { char: "况", pinyin: "kuàng", meaning: "situación (情况)" },
      { char: "继", pinyin: "jì", meaning: "continuar (继续)" },
      { char: "续", pinyin: "xù", meaning: "continuar (继续)" },
      { char: "内", pinyin: "nèi", meaning: "dentro / interior" },
      { char: "无", pinyin: "wú", meaning: "no tener / sin" },
      { char: "切", pinyin: "qiè", meaning: "cortar / (qiē) cortar" },
      { char: "由", pinyin: "yóu", meaning: "por / desde (causa)" },
      { char: "任", pinyin: "rèn", meaning: "cualquiera (任何) / confiar" },
      { char: "何", pinyin: "hé", meaning: "qué / cuál (任何)" },
      { char: "全", pinyin: "quán", meaning: "completo / todo" },
      { char: "计", pinyin: "jì", meaning: "contar / plan" },
      { char: "划", pinyin: "huà", meaning: "planear / trazar" },
      { char: "连", pinyin: "lián", meaning: "incluso / conectar" },
      { char: "呀", pinyin: "ya", meaning: "partícula exclamativa" },
      { char: "原", pinyin: "yuán", meaning: "original" },
      { char: "消", pinyin: "xiāo", meaning: "desaparecer / consumir" },
      { char: "受", pinyin: "shòu", meaning: "recibir / soportar" },
      { char: "功", pinyin: "gōng", meaning: "mérito / logro" },
      { char: "甚", pinyin: "shèn", meaning: "muy / incluso (甚至)" },
      { char: "至", pinyin: "zhì", meaning: "hasta / llegar" },
      { char: "拉", pinyin: "lā", meaning: "jalar / tirar" },
      { char: "肯", pinyin: "kěn", meaning: "estar dispuesto (肯定)" },
      { char: "部", pinyin: "bù", meaning: "parte / departamento" },
      { char: "式", pinyin: "shì", meaning: "estilo / fórmula" },
      { char: "处", pinyin: "chù", meaning: "lugar / (chǔ) manejar" },
      { char: "保", pinyin: "bǎo", meaning: "proteger (保护)" },
      { char: "持", pinyin: "chí", meaning: "sostener / mantener" },
      { char: "支", pinyin: "zhī", meaning: "sostener / rama / clasificador" },
      { char: "掉", pinyin: "diào", meaning: "caer / perder" },
      { char: "改", pinyin: "gǎi", meaning: "cambiar / corregir" },
      { char: "否", pinyin: "fǒu", meaning: "no (否则 / 是否)" },
      { char: "及", pinyin: "jí", meaning: "y / alcanzar" },
      { char: "制", pinyin: "zhì", meaning: "fabricar / sistema" },
      { char: "整", pinyin: "zhěng", meaning: "entero / ordenar" },
      { char: "组", pinyin: "zǔ", meaning: "grupo / organizar" },
      { char: "证", pinyin: "zhèng", meaning: "probar / certificado" },
      { char: "织", pinyin: "zhī", meaning: "tejer / organizar" },
      { char: "永", pinyin: "yǒng", meaning: "eterno / para siempre" },
      { char: "许", pinyin: "xǔ", meaning: "permitir / quizás (也许)" },
      { char: "虑", pinyin: "lǜ", meaning: "considerar (考虑)" },
      { char: "份", pinyin: "fèn", meaning: "clasificador (porciones)" },
      { char: "供", pinyin: "gōng", meaning: "proveer" },
      { char: "指", pinyin: "zhǐ", meaning: "dedo / señalar" },
      { char: "精", pinyin: "jīng", meaning: "esencia / espíritu (精神)" },
      { char: "神", pinyin: "shén", meaning: "dios / espíritu" },
      { char: "代", pinyin: "dài", meaning: "reemplazar / generación" },
      { char: "确", pinyin: "què", meaning: "cierto / verdadero (确实)" },
      { char: "标", pinyin: "biāo", meaning: "marca / estándar" },
      { char: "联", pinyin: "lián", meaning: "unir (联系)" },
      { char: "合", pinyin: "hé", meaning: "unir / combinar" },
      { char: "此", pinyin: "cǐ", meaning: "esto" },
      { char: "台", pinyin: "tái", meaning: "plataforma / clasificador (máquinas)" },
      { char: "获", pinyin: "huò", meaning: "obtener (获得)" },
      { char: "留", pinyin: "liú", meaning: "quedarse / dejar" },
      { char: "命", pinyin: "mìng", meaning: "vida / destino" },
      { char: "交", pinyin: "jiāo", meaning: "entregar / relacionarse" },
      { char: "另", pinyin: "lìng", meaning: "otro (además)" },
      { char: "血", pinyin: "xuè", meaning: "sangre" },
      { char: "挺", pinyin: "tǐng", meaning: "bastante / erguido" },
      { char: "克", pinyin: "kè", meaning: "gramo / superar" },
      { char: "底", pinyin: "dǐ", meaning: "fondo / base" },
      { char: "绝", pinyin: "jué", meaning: "absoluto / cortar (绝对)" },
      { char: "坚", pinyin: "jiān", meaning: "firme (坚持)" },
      { char: "座", pinyin: "zuò", meaning: "clasificador (asientos, edificios)" },
      { char: "技", pinyin: "jì", meaning: "habilidad (技术)" },
      { char: "术", pinyin: "shù", meaning: "técnica (技术)" },
      { char: "往", pinyin: "wǎng", meaning: "hacia / ir" },
      { char: "利", pinyin: "lì", meaning: "beneficio / ventaja" },
      { char: "严", pinyin: "yán", meaning: "estricto / severo" },
      { char: "括", pinyin: "kuò", meaning: "incluir (包括)" },
      { char: "光", pinyin: "guāng", meaning: "luz" },
      { char: "律", pinyin: "lǜ", meaning: "regla / ley" },
      { char: "父", pinyin: "fù", meaning: "padre" },
      { char: "亲", pinyin: "qīn", meaning: "padre-madre / cercano" },
      { char: "并", pinyin: "bìng", meaning: "además / y" },
      { char: "收", pinyin: "shōu", meaning: "recibir / cobrar" },
      { char: "社", pinyin: "shè", meaning: "sociedad (社会)" },
      { char: "管", pinyin: "guǎn", meaning: "manejar / tubo" },
      { char: "展", pinyin: "zhǎn", meaning: "desplegar / exhibir" },
      { char: "谈", pinyin: "tán", meaning: "conversar" },
      { char: "释", pinyin: "shì", meaning: "explicar (解释)" },
      { char: "负", pinyin: "fù", meaning: "cargar / negativo (负责)" },
      { char: "责", pinyin: "zé", meaning: "responsabilidad" },
      { char: "首", pinyin: "shǒu", meaning: "cabeza / primero" },
      { char: "排", pinyin: "pái", meaning: "fila / organizar" },
      { char: "量", pinyin: "liàng", meaning: "cantidad" },
      { char: "造", pinyin: "zào", meaning: "fabricar / crear" },
      { char: "梦", pinyin: "mèng", meaning: "sueño" },
      { char: "幸", pinyin: "xìng", meaning: "afortunado (幸福)" },
      { char: "福", pinyin: "fú", meaning: "felicidad / fortuna" },
      { char: "失", pinyin: "shī", meaning: "perder" },
      { char: "弄", pinyin: "nòng", meaning: "hacer / manipular" },
      { char: "赢", pinyin: "yíng", meaning: "ganar" },
      { char: "则", pinyin: "zé", meaning: "entonces / regla" },
    ]
  },
  {
    id: 5,
    name: "Nivel 5 · HSK 5 (Superior)",
    chars: [
      { char: "搞", pinyin: "gǎo", meaning: "hacer / manejar" },
      { char: "唯", pinyin: "wéi", meaning: "solo / único (唯一)" },
      { char: "政", pinyin: "zhèng", meaning: "política" },
      { char: "府", pinyin: "fǔ", meaning: "gobierno / residencia oficial" },
      { char: "统", pinyin: "tǒng", meaning: "unificar / sistema" },
      { char: "杀", pinyin: "shā", meaning: "matar" },
      { char: "拍", pinyin: "pāi", meaning: "golpear (palmada) / fotografiar" },
      { char: "控", pinyin: "kòng", meaning: "controlar" },
      { char: "存", pinyin: "cún", meaning: "existir / guardar" },
      { char: "哈", pinyin: "hā", meaning: "(risa) ja" },
      { char: "治", pinyin: "zhì", meaning: "gobernar / tratar (médico)" },
      { char: "疗", pinyin: "liáo", meaning: "tratar (médico, 治疗)" },
      { char: "拥", pinyin: "yōng", meaning: "abrazar / poseer (拥有)" },
      { char: "庭", pinyin: "tíng", meaning: "patio / (家庭) hogar" },
      { char: "显", pinyin: "xiǎn", meaning: "mostrar / evidente" },
      { char: "套", pinyin: "tào", meaning: "juego / clasificador (conjunto)" },
      { char: "曾", pinyin: "céng", meaning: "alguna vez (曾经)" },
      { char: "装", pinyin: "zhuāng", meaning: "vestir / instalar" },
      { char: "派", pinyin: "pài", meaning: "enviar / facción" },
      { char: "设", pinyin: "shè", meaning: "establecer / diseñar" },
      { char: "未", pinyin: "wèi", meaning: "todavía no" },
      { char: "倒", pinyin: "dào", meaning: "caer / al revés" },
      { char: "建", pinyin: "jiàn", meaning: "construir" },
      { char: "义", pinyin: "yì", meaning: "significado / justicia" },
      { char: "项", pinyin: "xiàng", meaning: "clasificador (proyectos) / partida" },
      { char: "某", pinyin: "mǒu", meaning: "cierto / tal" },
      { char: "训", pinyin: "xùn", meaning: "instruir (训练)" },
      { char: "似", pinyin: "sì", meaning: "parecerse (similar)" },
      { char: "宝", pinyin: "bǎo", meaning: "tesoro" },
      { char: "贝", pinyin: "bèi", meaning: "concha (宝贝)" },
      { char: "置", pinyin: "zhì", meaning: "colocar / ubicar" },
      { char: "秒", pinyin: "miǎo", meaning: "segundo (tiempo)" },
      { char: "属", pinyin: "shǔ", meaning: "pertenecer / signo zodiacal" },
      { char: "类", pinyin: "lèi", meaning: "tipo / categoría" },
      { char: "兄", pinyin: "xiōng", meaning: "hermano mayor" },
      { char: "夜", pinyin: "yè", meaning: "noche" },
      { char: "投", pinyin: "tóu", meaning: "lanzar / invertir" },
      { char: "析", pinyin: "xī", meaning: "analizar (分析)" },
      { char: "享", pinyin: "xiǎng", meaning: "disfrutar (享受)" },
      { char: "冠", pinyin: "guàn", meaning: "campeón (冠军)" },
      { char: "军", pinyin: "jūn", meaning: "ejército" },
      { char: "产", pinyin: "chǎn", meaning: "producir" },
      { char: "状", pinyin: "zhuàng", meaning: "forma / estado" },
      { char: "立", pinyin: "lì", meaning: "de pie / establecer" },
      { char: "抢", pinyin: "qiǎng", meaning: "arrebatar / robar" },
      { char: "傻", pinyin: "shǎ", meaning: "tonto" },
      { char: "救", pinyin: "jiù", meaning: "salvar / rescatar" },
      { char: "恢", pinyin: "huī", meaning: "restaurar (恢复)" },
      { char: "棒", pinyin: "bàng", meaning: "palo / genial (informal)" },
      { char: "致", pinyin: "zhì", meaning: "causar / enviar" },
      { char: "战", pinyin: "zhàn", meaning: "guerra / batalla" },
      { char: "构", pinyin: "gòu", meaning: "construir / estructura" },
      { char: "录", pinyin: "lù", meaning: "grabar / registrar" },
      { char: "冲", pinyin: "chōng", meaning: "enjuagar / cargar (impulso)" },
      { char: "待", pinyin: "dài", meaning: "esperar / tratar" },
      { char: "朝", pinyin: "cháo", meaning: "dinastía / hacia" },
      { char: "旦", pinyin: "dàn", meaning: "amanecer (元旦)" },
      { char: "承", pinyin: "chéng", meaning: "soportar / heredar" },
      { char: "执", pinyin: "zhí", meaning: "sostener / ejecutar" },
      { char: "痛", pinyin: "tòng", meaning: "dolor" },
    ]
  },
  {
    id: 6,
    name: "Nivel 6 · HSK 6 (Experto)",
    chars: [
      { char: "哦", pinyin: "ó", meaning: "¡ah! (interjección)" },
      { char: "啦", pinyin: "la", meaning: "partícula (contracción de 了+啊)" },
      { char: "嘛", pinyin: "ma", meaning: "partícula de énfasis obvio" },
      { char: "哇", pinyin: "wa", meaning: "¡wow! (interjección)" },
      { char: "亡", pinyin: "wáng", meaning: "morir / perder (灭亡)" },
      { char: "啥", pinyin: "shá", meaning: "qué (coloquial, = 什么)" },
      { char: "媒", pinyin: "méi", meaning: "intermediario (媒体 / 媒人)" },
      { char: "副", pinyin: "fù", meaning: "adjunto / clasificador (par)" },
      { char: "嗯", pinyin: "ń", meaning: "mmm (asentimiento)" },
      { char: "络", pinyin: "luò", meaning: "red (网络)" },
      { char: "伍", pinyin: "wǔ", meaning: "grupo militar / cinco (forma formal)" },
      { char: "攻", pinyin: "gōng", meaning: "atacar" },
      { char: "爆", pinyin: "bào", meaning: "estallar (爆炸)" },
      { char: "欧", pinyin: "ōu", meaning: "Europa (欧洲)" },
      { char: "央", pinyin: "yāng", meaning: "centro (中央)" },
      { char: "州", pinyin: "zhōu", meaning: "estado / prefectura" },
      { char: "袭", pinyin: "xí", meaning: "atacar por sorpresa" },
      { char: "诺", pinyin: "nuò", meaning: "prometer (承诺)" },
      { char: "砸", pinyin: "zá", meaning: "aplastar / fracasar" },
      { char: "党", pinyin: "dǎng", meaning: "partido (político)" },
      { char: "搭", pinyin: "dā", meaning: "construir / viajar en (搭车)" },
      { char: "盟", pinyin: "méng", meaning: "alianza" },
      { char: "仪", pinyin: "yí", meaning: "instrumento / ceremonia" },
      { char: "端", pinyin: "duān", meaning: "extremo / llevar (con las manos)" },
      { char: "盯", pinyin: "dīng", meaning: "mirar fijamente" },
      { char: "尸", pinyin: "shī", meaning: "cadáver" },
      { char: "异", pinyin: "yì", meaning: "diferente / extraño" },
      { char: "胞", pinyin: "bāo", meaning: "compatriota (同胞) / célula" },
      { char: "症", pinyin: "zhèng", meaning: "síntoma / enfermedad" },
      { char: "患", pinyin: "huàn", meaning: "padecer (enfermedad) / desastre" },
      { char: "艘", pinyin: "sōu", meaning: "clasificador (barcos)" },
      { char: "魂", pinyin: "hún", meaning: "alma" },
      { char: "枚", pinyin: "méi", meaning: "clasificador (objetos pequeños)" },
      { char: "凌", pinyin: "líng", meaning: "(凌晨) madrugada" },
      { char: "晨", pinyin: "chén", meaning: "amanecer (早晨)" },
      { char: "淘", pinyin: "táo", meaning: "(淘汰) eliminar" },
      { char: "汰", pinyin: "tài", meaning: "(淘汰) eliminar" },
      { char: "嗨", pinyin: "hāi", meaning: "¡hola! / ¡oye!" },
      { char: "予", pinyin: "yǔ", meaning: "dar / otorgar" },
      { char: "蹈", pinyin: "dǎo", meaning: "pisar (舞蹈)" },
      { char: "嘿", pinyin: "hēi", meaning: "¡oye! (interjección)" },
      { char: "哼", pinyin: "hēng", meaning: "resoplar (con desdén)" },
      { char: "障", pinyin: "zhàng", meaning: "obstáculo (障碍)" },
      { char: "索", pinyin: "suǒ", meaning: "cuerda / buscar (搜索)" },
      { char: "蒙", pinyin: "méng", meaning: "cubrir / engañar" },
      { char: "暴", pinyin: "bào", meaning: "violento / repentino" },
      { char: "尴", pinyin: "gān", meaning: "(尴尬) incómodo" },
      { char: "尬", pinyin: "gà", meaning: "(尴尬) incómodo" },
      { char: "婴", pinyin: "yīng", meaning: "bebé (婴儿)" },
      { char: "涉", pinyin: "shè", meaning: "involucrar (涉及)" },
    ]
  },
  {
    id: 7,
    name: "Nivel 7 · Clásico",
    chars: [
      { char: "矣", pinyin: "yǐ", meaning: "partícula final clásica (cambio de estado)" },
      { char: "兮", pinyin: "xī", meaning: "partícula exclamativa (poesía clásica)" },
      { char: "盖", pinyin: "gài", meaning: "tapa / probablemente (clásico)" },
      { char: "若", pinyin: "ruò", meaning: "si / como" },
      { char: "乃", pinyin: "nǎi", meaning: "entonces / ser (clásico)" },
      { char: "斯", pinyin: "sī", meaning: "esto (clásico)" },
      { char: "兹", pinyin: "zī", meaning: "esto / ahora (clásico)" },
      { char: "焉", pinyin: "yān", meaning: "dónde / ahí (clásico)" },
    ]
  },
  {
    id: 8,
    name: "Nivel 8 · Experto / Nicho",
    chars: [
      { char: "壹", pinyin: "yī", meaning: "uno (forma formal, documentos)" },
      { char: "贰", pinyin: "èr", meaning: "dos (forma formal)" },
      { char: "叁", pinyin: "sān", meaning: "tres (forma formal)" },
      { char: "肆", pinyin: "sì", meaning: "cuatro (forma formal) / desenfrenado" },
      { char: "陆", pinyin: "liù", meaning: "seis (forma formal) / tierra firme" },
      { char: "柒", pinyin: "qī", meaning: "siete (forma formal)" },
      { char: "捌", pinyin: "bā", meaning: "ocho (forma formal)" },
      { char: "玖", pinyin: "jiǔ", meaning: "nueve (forma formal)" },
      { char: "拾", pinyin: "shí", meaning: "diez (forma formal) / recoger" },
      { char: "仟", pinyin: "qiān", meaning: "mil (forma formal)" },
      { char: "佰", pinyin: "bǎi", meaning: "cien (forma formal)" },
      { char: "翰", pinyin: "hàn", meaning: "pluma / escrito (literario)" },
      { char: "墨", pinyin: "mò", meaning: "tinta" },
      { char: "砚", pinyin: "yàn", meaning: "piedra para tinta" },
      { char: "筝", pinyin: "zhēng", meaning: "guzheng (instrumento de cuerdas)" },
      { char: "琴", pinyin: "qín", meaning: "instrumento de cuerdas / piano" },
      { char: "瑟", pinyin: "sè", meaning: "instrumento de cuerdas antiguo" },
      { char: "箫", pinyin: "xiāo", meaning: "flauta vertical" },
      { char: "笛", pinyin: "dí", meaning: "flauta" },
      { char: "鼎", pinyin: "dǐng", meaning: "trípode ritual antiguo" },
      { char: "彧", pinyin: "yù", meaning: "refinado / culto (literario)" },
      { char: "翎", pinyin: "líng", meaning: "pluma de ave" },
      { char: "鸾", pinyin: "luán", meaning: "ave fénix mítica" },
      { char: "凰", pinyin: "huáng", meaning: "fénix (hembra mítica)" },
      { char: "麒", pinyin: "qí", meaning: "qilin (criatura mítica, macho)" },
      { char: "麟", pinyin: "lín", meaning: "qilin (criatura mítica, hembra)" },
    ]
  },
];
