// Datos de caracteres chinos (Hanzi) organizados por nivel de dificultad.
// Los niveles bajos contienen los caracteres más comunes y frecuentes;
// los niveles altos contienen caracteres más raros, formales o clásicos/literarios.

const LEVELS = [
  {
    id: 1,
    name: "Nivel 1 · Básico",
    chars: [
      { char: "我", pinyin: "wǒ", meaning: "yo" },
      { char: "你", pinyin: "nǐ", meaning: "tú" },
      { char: "他", pinyin: "tā", meaning: "él" },
      { char: "她", pinyin: "tā", meaning: "ella" },
      { char: "是", pinyin: "shì", meaning: "ser / estar" },
      { char: "不", pinyin: "bù", meaning: "no" },
      { char: "的", pinyin: "de", meaning: "partícula posesiva (de)" },
      { char: "了", pinyin: "le", meaning: "partícula de acción completada" },
      { char: "一", pinyin: "yī", meaning: "uno" },
      { char: "二", pinyin: "èr", meaning: "dos" },
      { char: "三", pinyin: "sān", meaning: "tres" },
      { char: "四", pinyin: "sì", meaning: "cuatro" },
      { char: "五", pinyin: "wǔ", meaning: "cinco" },
      { char: "六", pinyin: "liù", meaning: "seis" },
      { char: "七", pinyin: "qī", meaning: "siete" },
      { char: "八", pinyin: "bā", meaning: "ocho" },
      { char: "九", pinyin: "jiǔ", meaning: "nueve" },
      { char: "十", pinyin: "shí", meaning: "diez" },
      { char: "人", pinyin: "rén", meaning: "persona" },
      { char: "大", pinyin: "dà", meaning: "grande" },
      { char: "小", pinyin: "xiǎo", meaning: "pequeño" },
      { char: "好", pinyin: "hǎo", meaning: "bueno" },
      { char: "中", pinyin: "zhōng", meaning: "centro / medio" },
      { char: "国", pinyin: "guó", meaning: "país" },
      { char: "也", pinyin: "yě", meaning: "también" },
      { char: "很", pinyin: "hěn", meaning: "muy" },
      { char: "上", pinyin: "shàng", meaning: "arriba" },
      { char: "下", pinyin: "xià", meaning: "abajo" },
      { char: "去", pinyin: "qù", meaning: "ir" },
      { char: "来", pinyin: "lái", meaning: "venir" },
      { char: "天", pinyin: "tiān", meaning: "cielo / día" },
      { char: "年", pinyin: "nián", meaning: "año" },
      { char: "月", pinyin: "yuè", meaning: "mes / luna" },
      { char: "日", pinyin: "rì", meaning: "sol / día" },
      { char: "水", pinyin: "shuǐ", meaning: "agua" },
      { char: "火", pinyin: "huǒ", meaning: "fuego" },
      { char: "山", pinyin: "shān", meaning: "montaña" },
      { char: "门", pinyin: "mén", meaning: "puerta" },
      { char: "手", pinyin: "shǒu", meaning: "mano" },
      { char: "口", pinyin: "kǒu", meaning: "boca" },
      { char: "心", pinyin: "xīn", meaning: "corazón" },
      { char: "家", pinyin: "jiā", meaning: "casa / familia" },
      { char: "学", pinyin: "xué", meaning: "estudiar" },
      { char: "生", pinyin: "shēng", meaning: "nacer / vida" },
      { char: "女", pinyin: "nǚ", meaning: "mujer" },
      { char: "男", pinyin: "nán", meaning: "hombre" },
      { char: "子", pinyin: "zǐ", meaning: "hijo / niño" },
      { char: "老", pinyin: "lǎo", meaning: "viejo" },
      { char: "师", pinyin: "shī", meaning: "maestro" }
    ]
  },
  {
    id: 2,
    name: "Nivel 2 · Elemental",
    chars: [
      { char: "医", pinyin: "yī", meaning: "médico / medicina" },
      { char: "白", pinyin: "bái", meaning: "blanco" },
      { char: "黑", pinyin: "hēi", meaning: "negro" },
      { char: "红", pinyin: "hóng", meaning: "rojo" },
      { char: "会", pinyin: "huì", meaning: "saber (habilidad) / reunión" },
      { char: "想", pinyin: "xiǎng", meaning: "pensar / querer" },
      { char: "说", pinyin: "shuō", meaning: "decir" },
      { char: "看", pinyin: "kàn", meaning: "mirar / ver" },
      { char: "听", pinyin: "tīng", meaning: "escuchar" },
      { char: "吃", pinyin: "chī", meaning: "comer" },
      { char: "喝", pinyin: "hē", meaning: "beber" },
      { char: "走", pinyin: "zǒu", meaning: "caminar" },
      { char: "跑", pinyin: "pǎo", meaning: "correr" },
      { char: "坐", pinyin: "zuò", meaning: "sentarse" },
      { char: "站", pinyin: "zhàn", meaning: "estar de pie / parada" },
      { char: "开", pinyin: "kāi", meaning: "abrir" },
      { char: "关", pinyin: "guān", meaning: "cerrar" },
      { char: "买", pinyin: "mǎi", meaning: "comprar" },
      { char: "卖", pinyin: "mài", meaning: "vender" },
      { char: "多", pinyin: "duō", meaning: "mucho" },
      { char: "少", pinyin: "shǎo", meaning: "poco" },
      { char: "长", pinyin: "cháng", meaning: "largo" },
      { char: "高", pinyin: "gāo", meaning: "alto" },
      { char: "新", pinyin: "xīn", meaning: "nuevo" },
      { char: "旧", pinyin: "jiù", meaning: "viejo (objeto)" },
      { char: "冷", pinyin: "lěng", meaning: "frío" },
      { char: "热", pinyin: "rè", meaning: "caliente" },
      { char: "忙", pinyin: "máng", meaning: "ocupado" },
      { char: "累", pinyin: "lèi", meaning: "cansado" },
      { char: "睡", pinyin: "shuì", meaning: "dormir" },
      { char: "早", pinyin: "zǎo", meaning: "temprano" },
      { char: "晚", pinyin: "wǎn", meaning: "tarde / noche" },
      { char: "现", pinyin: "xiàn", meaning: "actual / presente" },
      { char: "时", pinyin: "shí", meaning: "tiempo / hora" },
      { char: "间", pinyin: "jiān", meaning: "intervalo / espacio" },
      { char: "今", pinyin: "jīn", meaning: "hoy" },
      { char: "明", pinyin: "míng", meaning: "claro / brillante" },
      { char: "昨", pinyin: "zuó", meaning: "ayer" },
      { char: "东", pinyin: "dōng", meaning: "este" },
      { char: "西", pinyin: "xī", meaning: "oeste" },
      { char: "南", pinyin: "nán", meaning: "sur" },
      { char: "北", pinyin: "běi", meaning: "norte" },
      { char: "里", pinyin: "lǐ", meaning: "dentro" },
      { char: "外", pinyin: "wài", meaning: "fuera" },
      { char: "前", pinyin: "qián", meaning: "adelante" },
      { char: "后", pinyin: "hòu", meaning: "atrás / después" },
      { char: "左", pinyin: "zuǒ", meaning: "izquierda" },
      { char: "右", pinyin: "yòu", meaning: "derecha" },
      { char: "用", pinyin: "yòng", meaning: "usar" }
    ]
  },
  {
    id: 3,
    name: "Nivel 3 · Intermedio",
    chars: [
      { char: "爱", pinyin: "ài", meaning: "amar" },
      { char: "喜", pinyin: "xǐ", meaning: "alegría / gustar" },
      { char: "欢", pinyin: "huān", meaning: "alegre / contento" },
      { char: "友", pinyin: "yǒu", meaning: "amigo" },
      { char: "朋", pinyin: "péng", meaning: "amigo (compañero)" },
      { char: "忘", pinyin: "wàng", meaning: "olvidar" },
      { char: "记", pinyin: "jì", meaning: "recordar / anotar" },
      { char: "懂", pinyin: "dǒng", meaning: "entender" },
      { char: "知", pinyin: "zhī", meaning: "saber" },
      { char: "道", pinyin: "dào", meaning: "camino / decir (razón)" },
      { char: "识", pinyin: "shí", meaning: "conocer / reconocer" },
      { char: "问", pinyin: "wèn", meaning: "preguntar" },
      { char: "答", pinyin: "dá", meaning: "responder" },
      { char: "题", pinyin: "tí", meaning: "pregunta / tema" },
      { char: "课", pinyin: "kè", meaning: "clase / lección" },
      { char: "本", pinyin: "běn", meaning: "libro / raíz" },
      { char: "书", pinyin: "shū", meaning: "libro" },
      { char: "纸", pinyin: "zhǐ", meaning: "papel" },
      { char: "笔", pinyin: "bǐ", meaning: "pluma / lápiz" },
      { char: "字", pinyin: "zì", meaning: "carácter / letra" },
      { char: "词", pinyin: "cí", meaning: "palabra" },
      { char: "语", pinyin: "yǔ", meaning: "idioma / lengua" },
      { char: "言", pinyin: "yán", meaning: "palabra / hablar" },
      { char: "文", pinyin: "wén", meaning: "escritura / cultura" },
      { char: "化", pinyin: "huà", meaning: "transformar / cambiar" },
      { char: "教", pinyin: "jiào", meaning: "enseñar" },
      { char: "育", pinyin: "yù", meaning: "educar" },
      { char: "校", pinyin: "xiào", meaning: "escuela" },
      { char: "班", pinyin: "bān", meaning: "clase / grupo" },
      { char: "级", pinyin: "jí", meaning: "grado / nivel" },
      { char: "考", pinyin: "kǎo", meaning: "examinar" },
      { char: "试", pinyin: "shì", meaning: "probar / examen" },
      { char: "习", pinyin: "xí", meaning: "practicar" },
      { char: "练", pinyin: "liàn", meaning: "entrenar" },
      { char: "钱", pinyin: "qián", meaning: "dinero" },
      { char: "店", pinyin: "diàn", meaning: "tienda" },
      { char: "市", pinyin: "shì", meaning: "mercado / ciudad" },
      { char: "场", pinyin: "chǎng", meaning: "lugar / campo" },
      { char: "公", pinyin: "gōng", meaning: "público" },
      { char: "司", pinyin: "sī", meaning: "gestionar / compañía" },
      { char: "工", pinyin: "gōng", meaning: "trabajo" },
      { char: "作", pinyin: "zuò", meaning: "hacer / trabajo" },
      { char: "业", pinyin: "yè", meaning: "profesión / industria" },
      { char: "休", pinyin: "xiū", meaning: "descansar" },
      { char: "息", pinyin: "xī", meaning: "descansar / respirar" },
      { char: "病", pinyin: "bìng", meaning: "enfermedad" },
      { char: "药", pinyin: "yào", meaning: "medicina" },
      { char: "院", pinyin: "yuàn", meaning: "patio / institución" },
      { char: "房", pinyin: "fáng", meaning: "habitación / casa" },
      { char: "桌", pinyin: "zhuō", meaning: "mesa" },
      { char: "椅", pinyin: "yǐ", meaning: "silla" },
      { char: "床", pinyin: "chuáng", meaning: "cama" }
    ]
  },
  {
    id: 4,
    name: "Nivel 4 · Avanzado",
    chars: [
      { char: "经", pinyin: "jīng", meaning: "experimentar / pasar por" },
      { char: "济", pinyin: "jì", meaning: "ayudar / economía" },
      { char: "政", pinyin: "zhèng", meaning: "política" },
      { char: "府", pinyin: "fǔ", meaning: "gobierno / residencia oficial" },
      { char: "法", pinyin: "fǎ", meaning: "ley / método" },
      { char: "律", pinyin: "lǜ", meaning: "norma / ley" },
      { char: "权", pinyin: "quán", meaning: "poder / derecho" },
      { char: "利", pinyin: "lì", meaning: "beneficio / ventaja" },
      { char: "益", pinyin: "yì", meaning: "beneficio / provecho" },
      { char: "害", pinyin: "hài", meaning: "daño / perjudicar" },
      { char: "危", pinyin: "wēi", meaning: "peligro" },
      { char: "险", pinyin: "xiǎn", meaning: "peligroso" },
      { char: "安", pinyin: "ān", meaning: "paz / seguro" },
      { char: "全", pinyin: "quán", meaning: "completo / todo" },
      { char: "必", pinyin: "bì", meaning: "necesariamente" },
      { char: "须", pinyin: "xū", meaning: "deber / necesitar" },
      { char: "应", pinyin: "yīng", meaning: "deber / responder" },
      { char: "该", pinyin: "gāi", meaning: "deber (debería)" },
      { char: "决", pinyin: "jué", meaning: "decidir" },
      { char: "定", pinyin: "dìng", meaning: "fijar / determinar" },
      { char: "选", pinyin: "xuǎn", meaning: "elegir" },
      { char: "择", pinyin: "zé", meaning: "escoger" },
      { char: "判", pinyin: "pàn", meaning: "juzgar" },
      { char: "断", pinyin: "duàn", meaning: "romper / decidir" },
      { char: "责", pinyin: "zé", meaning: "responsabilidad" },
      { char: "任", pinyin: "rèn", meaning: "confiar / tarea" },
      { char: "务", pinyin: "wù", meaning: "asunto / tarea" },
      { char: "职", pinyin: "zhí", meaning: "puesto / cargo" },
      { char: "位", pinyin: "wèi", meaning: "posición / lugar" },
      { char: "置", pinyin: "zhì", meaning: "colocar / ubicar" },
      { char: "设", pinyin: "shè", meaning: "establecer / diseñar" },
      { char: "计", pinyin: "jì", meaning: "contar / plan" },
      { char: "划", pinyin: "huà", meaning: "planear / trazar" },
      { char: "组", pinyin: "zǔ", meaning: "grupo / organizar" },
      { char: "织", pinyin: "zhī", meaning: "tejer / organizar" },
      { char: "系", pinyin: "xì", meaning: "sistema / atar" },
      { char: "统", pinyin: "tǒng", meaning: "unificar / sistema" },
      { char: "部", pinyin: "bù", meaning: "parte / departamento" },
      { char: "类", pinyin: "lèi", meaning: "tipo / categoría" },
      { char: "种", pinyin: "zhǒng", meaning: "tipo / semilla" },
      { char: "样", pinyin: "yàng", meaning: "forma / tipo" },
      { char: "式", pinyin: "shì", meaning: "estilo / fórmula" },
      { char: "形", pinyin: "xíng", meaning: "forma / figura" },
      { char: "状", pinyin: "zhuàng", meaning: "forma / estado" },
      { char: "态", pinyin: "tài", meaning: "actitud / estado" },
      { char: "度", pinyin: "dù", meaning: "grado / medida" },
      { char: "质", pinyin: "zhì", meaning: "calidad / sustancia" }
    ]
  },
  {
    id: 5,
    name: "Nivel 5 · Clásico",
    chars: [
      { char: "矣", pinyin: "yǐ", meaning: "partícula final clásica (cambio de estado)" },
      { char: "乎", pinyin: "hū", meaning: "partícula interrogativa clásica" },
      { char: "兮", pinyin: "xī", meaning: "partícula exclamativa (poesía clásica)" },
      { char: "夫", pinyin: "fū", meaning: "marido / partícula introductoria clásica" },
      { char: "盖", pinyin: "gài", meaning: "tapa / probablemente (clásico)" },
      { char: "若", pinyin: "ruò", meaning: "si / como" },
      { char: "乃", pinyin: "nǎi", meaning: "entonces / ser (clásico)" },
      { char: "其", pinyin: "qí", meaning: "su / eso (clásico)" },
      { char: "之", pinyin: "zhī", meaning: "de / eso (partícula clásica)" },
      { char: "者", pinyin: "zhě", meaning: "el que / la persona que" },
      { char: "所", pinyin: "suǒ", meaning: "lugar / lo que" },
      { char: "斯", pinyin: "sī", meaning: "esto (clásico)" },
      { char: "兹", pinyin: "zī", meaning: "esto / ahora (clásico)" },
      { char: "焉", pinyin: "yān", meaning: "dónde / ahí (clásico)" }
    ]
  },
  {
    id: 6,
    name: "Nivel 6 · Experto / Nicho",
    chars: [
      { char: "壹", pinyin: "yī", meaning: "uno (forma formal, documentos)" },
      { char: "贰", pinyin: "èr", meaning: "dos (forma formal)" },
      { char: "叁", pinyin: "sān", meaning: "tres (forma formal)" },
      { char: "肆", pinyin: "sì", meaning: "cuatro (forma formal) / desenfrenado" },
      { char: "伍", pinyin: "wǔ", meaning: "cinco (forma formal) / grupo militar" },
      { char: "陆", pinyin: "liù", meaning: "seis (forma formal) / tierra firme" },
      { char: "柒", pinyin: "qī", meaning: "siete (forma formal)" },
      { char: "捌", pinyin: "bā", meaning: "ocho (forma formal)" },
      { char: "玖", pinyin: "jiǔ", meaning: "nueve (forma formal)" },
      { char: "拾", pinyin: "shí", meaning: "diez (forma formal) / recoger" },
      { char: "仟", pinyin: "qiān", meaning: "mil (forma formal)" },
      { char: "佰", pinyin: "bǎi", meaning: "cien (forma formal)" },
      { char: "翰", pinyin: "hàn", meaning: "pluma / escrito (literario)" },
      { char: "墨", pinyin: "mò", meaning: "tinta" },
      { char: "砚", pinyin: "yàn", meaning: "piedra para tinta" },
      { char: "筝", pinyin: "zhēng", meaning: "guzheng (instrumento de cuerdas)" },
      { char: "琴", pinyin: "qín", meaning: "instrumento de cuerdas / piano" },
      { char: "瑟", pinyin: "sè", meaning: "instrumento de cuerdas antiguo" },
      { char: "箫", pinyin: "xiāo", meaning: "flauta vertical" },
      { char: "笛", pinyin: "dí", meaning: "flauta" },
      { char: "鼎", pinyin: "dǐng", meaning: "trípode ritual antiguo" },
      { char: "彧", pinyin: "yù", meaning: "refinado / culto (literario)" },
      { char: "翎", pinyin: "líng", meaning: "pluma de ave" },
      { char: "鸾", pinyin: "luán", meaning: "ave fénix mítica" },
      { char: "凰", pinyin: "huáng", meaning: "fénix (hembra mítica)" },
      { char: "麒", pinyin: "qí", meaning: "qilin (criatura mítica, macho)" },
      { char: "麟", pinyin: "lín", meaning: "qilin (criatura mítica, hembra)" }
    ]
  }
];
